### ISSUE TITLE
Integrating variables and ad hoc filters

### ISSUE THREAD

**Issue by raulsperoni** [cloudspout/cloudspout-button-panel#11]
Hi! First thank you, this is a great plugin. I'm using grafana for some admin tasks and this is very useful.

For my needs I forked and modified your code. 

In the editor I allow to add other kind of parameters: "variable parameters" that will be resolved before the request. Also I allow to use the variable notation in the label of the button. "This is the label for $variable"

In the panel I'm resolving the variables configured in the editor: first I look for ad hoc filters (I use them in elasticsearch) then for regular variables like text box variables.

The use case form me is the ability to invoke an endpoint with current dashboard filters and variables.

What do you think? would you be interested in a pull request?

**Comment by derjust** [comment]
I can totally see the use case for Grafana variables.
I'm more than happy to accept PRs - I created this plugin for my very simple use case but happy to extend it

**Comment by derjust** [comment]
Variables in the Button text should work now

**Comment by richimus123** [comment]
Awesome, I was just wondering if this was in the works. Any ETA on when this would make it into a release?

**Comment by derjust** [comment]
It is in the current release if you install it manually as described on the home page.
Installing via the Grafana web site itself is waiting for this: https://github.com/grafana/grafana-plugin-repository/pull/756

**Comment by derjust** [comment]
Using `templateSrv` should address the use case - have to re-check the PR if I missed something

**Comment by richimus123** [comment]
From your release notes, this adds support for variables in the following ways:
* Variable support via `$variableName` in
    * URL
    * parameter name & value
    * Button label

Any chance of adding support in the payload as well? Should I open a different enhancement request?

**Comment by derjust** [comment]
That shouldn't be too hard actually. I will give it a shot

**Comment by danielloader** [comment]
Hey sorry to reopen this, I'm trying to get the email address of the current user, and send it as a header using the button Webhook plugin, but when I send the header with a value of ${__user.email} I get a numeric ID, same as ${__user}, expected behaviour? 
This is on Grafana cloud.
