### ISSUE TITLE
Support Basic Auth (was: No chance to Connect to Node-Red on my Raspberry)

### ISSUE THREAD

**Issue by runout0** [cloudspout/cloudspout-button-panel#15]
Hi,

use grafana-button-panel Version 7.03.
No GET-Action is possible.
The Node-Red Setup is already done.
curl -u node_red_xxxxx:pw_node_red_xxxxx -i -s localhost:1880/btn01 - works fine
curl node_red_xxxxx:pw_node_red_xxxxx@localhost:1880/btn01?wert=44  - works fine
http://node_red_xxxxx:pw_node_red_xxxxx@192.168.29.52:1880/btn01  - works fine from a remote Browser

cloudspout-button-panel does literally nothing...
use grafana 7.1.0
basic auth for Node-Red Access is required.

Any Idea to get running the Button?
Or: What is the clean path to uninstall the button-panel?

Kind regards
runout

**Comment by derjust** [comment]
To uninstall the plugin, run 
```grafana-cli plugins uninstall cloudspout-button-panel```

Due to security features implemented in modern browsers (CORS), credentials in the URL are less supported.
(Basic) Auth should be added to the plugin additional to the API-Key header
