### ISSUE TITLE
No Options Present in Grafana 7.2.0

### ISSUE THREAD

**Issue by jaydizz** [cloudspout/cloudspout-button-panel#17]
Hi, 
First: Thanks for developing this plugin. It would be perfect for my needs. 
However, after I installed version 7.0.4 of the plugin for grafana 7.2.0 I noticed that the "Options" dialog is missing after selecting "Button Panel" as visualization. (Also see the screenshot below). 
Without this, configuration is impossible. 
Can you please have a look at this behaviour?

Thanks in advance! 
![Cheese_Thu-01Oct20_16 49](https://user-images.githubusercontent.com/29492311/94825277-43476780-0406-11eb-9121-53afea1e3a48.png)

**Comment by derjust** [comment]
Can confirm. 
It works in Grafana 7.0.x and 7.1.x

Looking into it. 
Thank you for reporting

**Comment by Alexandero89** [comment]
Hey @derjust ,

this is my console output when trying to add it:  
`[Deprecation warning] PanelPlugin: setDefaults is deprecated. Use setPanelOptions instead deprecationWarning.ts:14:12  `

Hope this helps, but i think you found that too.
