### ISSUE TITLE
Rest integration now showing

### ISSUE THREAD

**Issue by Wailshire** [cloudspout/cloudspout-button-panel#23]
Hello, i installed multiple times the button to do post request, but today i installed it, and there is no option for the rest integration, the button shows in the dashboard, but i dont have any options to edit it, i cant even change the text. is there a new update or im missing something? 
Thanks !

**Comment by Wailshire** [comment]
nevermind, i used the link provided by grafana to install the plugin, but now i used the one for this repository and worked perfectly, i think the grafana link is outdated

**Comment by JnMik** [comment]
Thanks, so we just need to install it from the git clone command in the proper folder and run the yarn commands, right ? 
I'll test that

**Comment by derjust** [comment]
@Wailshire Yes the [new version](https://github.com/grafana/grafana-plugin-repository/pull/756) is pending addition to Grafana. 
Using the Grafana CLI to install the new version directly works to get the new version:
```
grafana-cli --pluginUrl https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.5/cloudspout-button-panel.zip \
  plugins install cloudspout-button-panel
```

**Comment by JnMik** [comment]
Yep I got it working, thanks guys :)

So I managed to control a digital output (let's say it could be a light), be creating 2 buttons to control it, and one stats panels to show its state.

![ss1](https://user-images.githubusercontent.com/4965516/97128105-d3c94d00-1711-11eb-8278-d059764b7ace.png)

Imagine if your button could have a "GET" separate http call to fetch its status and choose a color according to the response, all of this could be merge in 1 button :P

Just an idea, in case in could touch your heart @derjust  :D lol ! 

Thanks guys

**Comment by derjust** [comment]
@JnMik 
Yes you can also use 
```
git clone
```
But probably the Grafana CLI is easier to use
```
grafana-cli --pluginUrl https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.5/cloudspout-button-panel.zip \
  plugins install cloudspout-button-panel
```
or the following ENV variable (works also for Grafana-in-Docker):
`GF_INSTALL_PLUGINS=https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.5/cloudspout-button-panel.zip;cloudspout-button-panel`

**Comment by derjust** [comment]
> Imagine if your button could have a "GET" separate http call to fetch its status and choose a color according to the response, all of this could be merge in 1 button :P

I will think about it - but this combo of 3 items is what I have, too (Note: Turning the panel of the button transparent makes them look a bit nicer):
<img width="219" alt="Screen Shot 2020-10-25 at 11 03 13 PM" src="https://user-images.githubusercontent.com/2053353/97129893-5eac4680-1716-11eb-9704-7c6cbe1c330e.png">
