### ISSUE TITLE
button panel 7.0.7 packaging for grafana direct installation seems to be incomplete

### ISSUE THREAD

**Issue by andreacolpo** [cloudspout/cloudspout-button-panel#29]
Hi guys, 
i have tried to install this plugin packaged here (https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.7/cloudspout-button-panel.zip) through normal grafana process installation, that is :

- extract your zip under the path : /var/lib/grafana/plugins and assigning grafana:grafana user:group owners
- restarted grafana

But going to grafana plugin page i see the message "Error loading plugin. check the server startup logs for more information. if this plugin was loaded from git, make sure it was compiled". 

![immagine](https://user-images.githubusercontent.com/54848152/97288422-1c822280-1846-11eb-8234-19eefeab2d11.png)

So is there no a zip file already prepared for the grafana installation ?

I have also tried to change current cors status for my firefox (versione 82.0 64bit) (https://www.google.com/search?client=firefox-b-d&q=firefox+enable+cors) but without success.

OS version : Redhat 7.7

From grafana log i see only this without any errors...

[root@node001 grafana]# grep -i button grafana.log
t=2020-10-27T06:42:53-0300 lvl=info msg="Registering plugin" logger=plugins name="Button Panel"
[root@node001 grafana]#

Thanks for any feedback.
Regards

**Comment by derjust** [comment]
Which Grafana version are you using?

Can you do a `ls -laR` of your `/var/lib/grafana/plugins` folder?

It should look like this:
```
$  plugins ls -laR
total 0
drwxr-xr-x    3 grafana  grafana     96 Nov  1 12:56 .
drwx------+ 352 grafana  grafana  11264 Nov  1 12:56 ..
drwxr-xr-x@  11 grafana  grafana    352 Oct 15 12:13 cloudspout-button-panel

./cloudspout-button-panel:
total 264
drwxr-xr-x@ 11 grafana  grafana    352 Oct 15 12:13 .
drwxr-xr-x   3 grafana  grafana     96 Nov  1 12:56 ..
-rw-r--r--@  1 grafana  grafana  35149 Oct 15 12:23 LICENSE
-rw-r--r--@  1 grafana  grafana   3330 Oct 15 12:23 README.md
drwxr-xr-x@  5 grafana  grafana    160 Nov  1 12:53 img
-rw-r--r--@  1 grafana  grafana    183 Oct 10 21:37 index.html
-rw-r--r--@  1 grafana  grafana  15567 Oct 15 12:23 module.js
-rw-r--r--@  1 grafana  grafana    808 Oct 15 12:23 module.js.LICENSE.txt
-rw-r--r--@  1 grafana  grafana  65001 Oct 15 12:23 module.js.map
-rw-r--r--@  1 grafana  grafana    979 Oct 15 12:23 plugin.json
drwxr-xr-x@  3 grafana  grafana     96 Jun 20 03:58 static

./cloudspout-button-panel/img:
total 264
drwxr-xr-x@  5 grafana  grafana     160 Nov  1 12:53 .
drwxr-xr-x@ 11 grafana  grafana     352 Oct 15 12:13 ..
-rw-r--r--@  1 grafana  grafana    3020 Oct 15 12:23 logo.svg
-rw-r--r--@  1 grafana  grafana    3020 Jul 22 02:50 method-draw-image.svg
-rw-r--r--@  1 grafana  grafana  124138 Oct 15 12:23 screenshot.png

./cloudspout-button-panel/static:
total 8
drwxr-xr-x@  3 grafana  grafana   96 Jun 20 03:58 .
drwxr-xr-x@ 11 grafana  grafana  352 Oct 15 12:13 ..
-rw-r--r--@  1 grafana  grafana  330 Oct 15 12:23 button-panel.css
```
Is it maybe double-wrapped in a folder? I just downloaded the `7.0.7` release and tested with Grafana 7.2.0 not being able to reproduce it.

**Comment by derjust** [comment]
There is also the new Plugin version now available directly via Grafana. Hope that one helps, too!
