### ISSUE TITLE
Sign plugin

### ISSUE THREAD

**Issue by derjust** [cloudspout/cloudspout-button-panel#3]
Grafana 7 comes with a signing feature for plugins.
There is no process for community plugins yet:
https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#:~:text=Signing%20a%20plugin%20allows%20Grafana,including%20Enterprise%20plugins%2C%20are%20signed.

**Comment by 1nv1** [comment]
In 7.3.1 isn't possible configure the plugin 
![imagen](https://user-images.githubusercontent.com/2840417/98178000-94052100-1eda-11eb-9db2-7fede609b24f.png)

**Comment by derjust** [comment]
Published public key `B7E1 0763 4FB7 DB72 3404  3E9F 96DF 230F DC0E C9C6`
Also available via [`keybase://public/zeeman/public.asc`](https://keybase.pub/zeeman/public.asc)

**Comment by derjust** [comment]
Successfully signed a release locally. Applied for public API key via email as per https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#sign-a-public-plugin

**Comment by derjust** [comment]
As a temporary workaround, use the setting [allow_loading_unsigned_plugins](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins)

or the ENV variable
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=cloudspout-button-panel
```
to deactivate signature checking for this plugin.

**Comment by derjust** [comment]
Version `7.0.19` is the first one that is properly signed by [cloudspout](https://grafana.com/orgs/cloudspout)
