### ISSUE TITLE
Wrong 'Authorization' header for the 'Basic' authentication scheme 

### ISSUE THREAD

**Issue by kochetov-dmitrij** [cloudspout/cloudspout-button-panel#33]
Add 'Basic ' in https://github.com/cloudspout/cloudspout-button-panel/blob/743a01b174358bce41d39302ebc1dfae06f272e8/src/ButtonPanel.tsx#L52
Solution:
```js
requestHeaders.set('Authorization', 'Basic ' + btoa(options.username + ':' + options.password));
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

**Comment by derjust** [comment]
Thanks for reporting. Fixed in 6ba38a0
