### ISSUE TITLE
Button style (how to remove the 'check' logo)

### ISSUE THREAD

**Issue by JJayyyy** [cloudspout/cloudspout-button-panel#35]
Hi, @derjust  Thanks for the contributions!
I am using your button now. But I don't expect to see the "check" logo after successful request, do you know where to edit the related codes?

![image](https://user-images.githubusercontent.com/46363767/100041595-9fe26400-2e44-11eb-8187-e2e7e4265b3d.png)

**Comment by derjust** [comment]
The checkmark is presented after the button click was communicated to the server successfully.
(In case of a failure, a warning sign is shown).

The change daafd5b resets the button to its configured state after 2.5s.
This gives the user the visual feedback if the call was successful or not but also restores the visual state eventually
