### ISSUE TITLE
Use button for navigation

### ISSUE THREAD

**Issue by florianwgnr** [cloudspout/cloudspout-button-panel#5]
So far the button supports HTTP GET and POST, which is great - many thanks!

It would be even better to use it as a navigation button, where it navigates the browser to a specific URL (or dashboard-id). 

Why? Because this button looks nicer than the integrated link buttons.

The easiest way might be just a link-field.

**Comment by derjust** [comment]
The intention of the button is explicitly to do an  Ajax request that has no impact on the current view of the Browser - I'm not sure if your proposal falls into the scope

**Comment by SorryGames** [comment]
> The intention of the button is explicitly to do an Ajax request that has no impact on the current view of the Browser - I'm not sure if your proposal falls into the scope

I got the idea of your project, but if you can... Actually, Grafana has no plugins are related to buttons with links (markdown links and html tags in Text plugin is not a simple and beautiful solution). However, at the first glance your project has so many ways to customize buttons, so your project could be grate solution for button links.
