### ISSUE TITLE
Multiple buttons

### ISSUE THREAD

**Issue by Webbeh** [cloudspout/cloudspout-button-panel#7]
Hi,

Thank you for this plugin.

Would it be hard to implement multiple buttons support in the same panel ?

Their ordering could be left-to-right or top-to-bottom and ideally they'd all have the same width/height in the same panel. Obviously, separate HTTP requests per button.

This would help getting rid of the panel title bar.
Thank you !

**Comment by derjust** [comment]
I'm sorry but I don't see this to be implemented.
A button component can be added multiple times into the same dashboard addressing this requirement.
