### ISSUE TITLE
Choice of icons & color

### ISSUE THREAD

**Issue by Webbeh** [cloudspout/cloudspout-button-panel#8]
Hi

Me again.

Would it be possible to add a way for the user to choose the icon that shows on the left of the button ? 
Maybe using fontawesome could be enough, but it'd be nice to have the choice of custom icon as well.

Also, a customisation of the colors of the button would be nice.

Thank you again !

**Comment by derjust** [comment]
Here we go:
Grafana comes with a list of Icons - so re-using those & the ability to specify custom colors:
(A preview of the icon in the selectbox is not possible as the Grafana API doesn't allow for such an element).
![Color_and_Icon](https://user-images.githubusercontent.com/2053353/95665262-b181dd80-0b1c-11eb-944b-b25343d3c708.gif)

**Comment by derjust** [comment]
Fixed with PR #8

**Comment by Webbeh** [comment]
Thank you!
